name: "Testing"

on:
  push:
    branches:
      - main
env:
  DEV_VAR: ${{ vars.DEV_VAR }}
  TEST_VAR: ${{ vars.TEST_VAR }}

jobs:
  testing:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Display env
        run: echo '${{ toJSON(env) }}'

      - name: Dev
        run: echo $DEV_VAR
      - name: Test
        run: echo $TEST_VAR

      # - name: Display secret
      #   run: echo '${{ toJSON(secret) }}'
      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'
      # - name: Dump job context
      #   run: echo '${{ toJSON(job) }}'
      # - name: Dump steps context
      #   run: echo '${{ toJSON(steps) }}'
      # - name: Dump runner context
      #   run: echo '${{ toJSON(runner) }}'
      # - name: Dump strategy context
      #   run: echo '${{ toJSON(strategy) }}'
      # - name: Dump matrix context
      #   run: echo '${{ toJSON(matrix) }}'