name: "Testing"

on:
 push:
    branches:
      - main
jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref.name }}

      - name: Add sanitize branch to vars
        run: |-
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          echo GITHUB_REF_SANITIZE=$(echo ${BRANCH_NAME//[\/_]/-} | tr '[:upper:]' '[:lower:]' | cut -c -40 | sed 's/\-$//') >> $GITHUB_ENV

      - name: echo
        run: |
          echo ${{ env.GITHUB_REF_SANITIZE }} 
      - name: echo2
        run: |
          echo ${{ env.GITHUB_REF_SANITIZE }}
