name: "Testing"

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          echo ${{ GITHUB_REF_NAME }}