name: "Testing"

on:
  push:
    branches:
      - main
env:
  
  
  
  
  

jobs:
  testing:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dev var
        run: echo $DEV_VAR
        env:
          DEV_VAR: ${{ vars.DEV_VAR }}

      - name: Test var
        run: echo $TEST_VAR
        env:
          TEST_VAR: ${{ vars.TEST_VAR }}

      - name: Dev sec
        run: echo $DEV_SECRET
        env: 
          DEV_SECRET: ${{ secrets.DEV_SECRET}}

      - name: Test sec
        run: echo $TEST_SECRET
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET}}

      # - name: Display secret
      #   run: echo '${{ toJSON(secret) }}'
      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'
      # - name: Dump job context
      #   run: echo '${{ toJSON(job) }}'
      # - name: Dump steps context
      #   run: echo '${{ toJSON(steps) }}'
      # - name: Dump runner context
      #   run: echo '${{ toJSON(runner) }}'
      # - name: Dump strategy context
      #   run: echo '${{ toJSON(strategy) }}'
      # - name: Dump matrix context
      #   run: echo '${{ toJSON(matrix) }}'