name: "Testing"

on:
 push:
    branches:
      - main
jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref.name }}
       
      - name: Add sanitize branch to vars
        run: |-
          MERGE_COMMIT_MESSAGE=$(git log --format=%B -n 1 "${GITHUB_SHA}")
          BRANCH_NAME=$(echo "$MERGE_COMMIT_MESSAGE" | grep -oP '(?<=from ).*' | awk -F/ '{print $NF}')
          echo "Branch Name: $BRANCH_NAME"
          echo GITHUB_REF_SANITIZE4=$(echo ${BRANCH_NAME//[\/_]/-} | tr '[:upper:]' '[:lower:]' | cut -c -40 | sed 's/\-$//') >> $GITHUB_ENV


