name: "Testing"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment


jobs:
  testing:
    runs-on: "ubuntu-latest"
    # environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref.name }}

      - name: Set var
        run: |
          echo  "MY_TABEL="TestValue"'>> $GITHUB_ENV

      - name: echo var
        run: |
          echo $MY_TABEL

      - name: test condition
        if: contains( env.MY_TABEL , 'supply')
        run: |
          echo "Mamy to: $MY_TABEL"

      # - name: GITHUB_WORKFLOW_REF
      #   run: |
      #     echo $GITHUB_WORKFLOW_REF

      # - name: GITHUB_REF_NAME
      #   run: |
      #     echo $GITHUB_REF_NAME

      # - name: GITHUB_REF
      #   run: |
      #     echo $GITHUB_REF      
          
      # - name: GITHUB_HEAD_REF
      #   run: |
      #     echo $GITHUB_HEAD_REF
      
      # - name: Echo env vars
      #   run: |
      #     echo ${{ vars.PROJECT_ID }}

      # - name: Add var via bash
      #   run: |
      #     echo "GITHUB_REF_SANITIZE=${GITHUB_REF//[\/_]/-}" >> $GITHUB_ENV

      # - name: Echo new env
      #   run: |
      #     echo ${{ env.GITHUB_REF_SANITIZE }}