name: "Testing"

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.branchName }}