name: "Testing"

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name to deploy'
        required: true
jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.branchName }}