name: "Testing"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment


jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref.name }}

      - uses: 'google-github-actions/auth@v1'
        id: 'auth'
        name: 'Auth to GCP'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 416.0.0'

      - name: assigne test
        run: |
          service=`gcloud run services list --format=json | jq -r '.[].metadata | select(.name == "supply")| .name'`
          if [ "supply" = $service ]; then
            echo "WYNIK1=1" >> $GITHUB_ENV
          else
            echo "WYNIK1=0" >> $GITHUB_ENV
          fi
          echo ${{ env.MY_REF }}
          echo $MY_REF
        env:
          MY_REF: ${{ inputs.environment }}


      # - name: Set var
      #   run: |
      #     echo  'MY_TABEL=supply4" "supply2" "supply3"'>> $GITHUB_ENV

      # - name: echo var
      #   run: |
      #     echo $MY_TABEL

      # - name: test condition
      #   if: contains( env.MY_TABEL , 'supply5')
      #   run: |
      #     echo "Mamy to: $MY_TABEL"

      # - name: echo env
      #   run: |
      #     echo ${{ inputs.environment }}

      # - name: assigne test
      #   run: |-
      #     a=$(ls -l)
      #     if [[-z "$a"]]; then
      #       echo 'WYNIK1=$?' >> $GITHUB_ENV 
      #     else 
      #       echo 'WYNIK1=$?' >> $GITHUB_ENV
      #     fi
      #     echo 'WYNIK2=$a' >> $GITHUB_ENV

      - name: echo my_ref
        run: |
          echo ${{ env.MY_REF }}
      - name: echo my_ref
        run: |
          echo ${{ env.WYNIK1 }}

      # - name: GITHUB_WORKFLOW_REF
      #   run: |
      #     echo $GITHUB_WORKFLOW_REF

      # - name: GITHUB_REF_NAME
      #   run: |
      #     echo $GITHUB_REF_NAME

      # - name: GITHUB_REF
      #   run: |
      #     echo $GITHUB_REF      
          
      # - name: GITHUB_HEAD_REF
      #   run: |
      #     echo $GITHUB_HEAD_REF
      
      # - name: Echo env vars
      #   run: |
      #     echo ${{ vars.PROJECT_ID }}

      # - name: Add var via bash
      #   run: |
      #     echo "GITHUB_REF_SANITIZE=${GITHUB_REF//[\/_]/-}" >> $GITHUB_ENV

      # - name: Echo new env
      #   run: |
      #     echo ${{ env.GITHUB_REF_SANITIZE }}