name: "Testing"

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref.name }}

      - name: GITHUB_WORKFLOW_REF
        run: |
          echo $GITHUB_WORKFLOW_REF
      - name: GITHUB_REF_NAME
        run: |
          echo $GITHUB_REF_NAME
      - name: GITHUB_REF
        run: |
          echo $GITHUB_REF      
      - name: GITHUB_HEAD_REF
        run: |
          echo $GITHUB_HEAD_REF