name: "Testing"

on:
 push:
    branches:
      - main
jobs:
  testing:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref.name }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Add sanitize branch to vars
        run: |-
          BRANCH_NAME=${{ github.ref }}
          echo GITHUB_REF_SANITIZE1=$(echo ${BRANCH_NAME//[\/_]/-} | tr '[:upper:]' '[:lower:]' | cut -c -40 | sed 's/\-$//') >> $GITHUB_ENV
      
      - name: Add sanitize branch to vars
        run: |-
          BRANCH_NAME=${{ github.ref_name }}
          echo GITHUB_REF_SANITIZE2=$(echo ${BRANCH_NAME//[\/_]/-} | tr '[:upper:]' '[:lower:]' | cut -c -40 | sed 's/\-$//') >> $GITHUB_ENV
      
      - name: Add sanitize branch to vars
        run: |-
          BRANCH_NAME=${{ github.base_ref }}
          echo GITHUB_REF_SANITIZE3=$(echo ${BRANCH_NAME//[\/_]/-} | tr '[:upper:]' '[:lower:]' | cut -c -40 | sed 's/\-$//') >> $GITHUB_ENV
      - name: Add sanitize branch to vars
        run: |-
          BRANCH_NAME=${{ github.head_ref }}
          echo GITHUB_REF_SANITIZE4=$(echo ${BRANCH_NAME//[\/_]/-} | tr '[:upper:]' '[:lower:]' | cut -c -40 | sed 's/\-$//') >> $GITHUB_ENV

      - name: echo1
        run: |
          echo ${{ env.GITHUB_REF_SANITIZE1 }}
          
      - name: echo2
        run: |
          echo ${{ env.GITHUB_REF_SANITIZE2 }}

      - name: echo3
        run: |
          echo ${{ env.GITHUB_REF_SANITIZE3 }}
      - name: echo4
        run: |
          echo ${{ env.GITHUB_REF_SANITIZE4 }}
